CREATE DATABASE UPROTOCOL;

CREATE TABLE EMPRESA (
	ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    CNPJ_CPF VARCHAR(18),
    RAZAOSOCIAL VARCHAR(100),
    FANTASIA VARCHAR(100),
    CRIADOR INT,
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT
    );

CREATE TABLE CONTA (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    CLOGIN VARCHAR(100),
    SENHA VARCHAR(100)
);

CREATE TABLE SETOR (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    NOME VARCHAR(100),
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_SETOR FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    CONTA INT,
    SETOR INT,
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    CARGO VARCHAR(100),
    CONSTRAINT FK_CONTA_USUARIO FOREIGN KEY (CONTA) REFERENCES CONTA(ID),
    CONSTRAINT FK_SETOR_USUARIO FOREIGN KEY (SETOR) REFERENCES SETOR(ID)
);

CREATE TABLE USUARIOEMPRESA (
    ID SERIAL PRIMARY KEY NOT NULL,
    EMPRESA INT,
    USUARIO INT,
    CONSTRAINT FK_EMPRESA_USUARIO FOREIGN KEY (EMPRESA) REFERENCES EMPRESA(ID),
    CONSTRAINT FK_USUARIO_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    RAZAOSOCIAL VARCHAR(100),
    FANTASIA VARCHAR(100),
    CNPJ_CPF VARCHAR(18),
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_CLIENTE FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE PRIORIDADE (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    NOME VARCHAR(100),
    ORDEMIMPORTANCIA INT,
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_PRIORIDADE FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE PROTOCOLO (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATENDENTE INT,
    CLIENTE INT,
    SITUACAO CHAR,
    PRIORIDADE INT,
    PESSOAATENDIDA VARCHAR(100),
    MOTIVO VARCHAR(100),
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_PROTOCOLO FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID),
    CONSTRAINT FK_ATENDENTE_PROTOCOLO FOREIGN KEY (ATENDENTE) REFERENCES USUARIO (ID),
    CONSTRAINT FK_CLIENTE_PROTOCOLO FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID),
    CONSTRAINT FK_PRIORIDADE_PROTOCOLO FOREIGN KEY (PRIORIDADE) REFERENCES PRIORIDADE (ID)
);

CREATE TABLE REPASSE (
    ID SERIAL PRIMARY KEY NOT NULL,
    USUARIOATUAL INT,
    PROTOCOLO INT,
    USUARIODESTINO INT,
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_REPASSE FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID),
    CONSTRAINT FK_PROTOCOLO_REPASSE FOREIGN KEY (PROTOCOLO) REFERENCES PROTOCOLO (ID)
);

CREATE TABLE CONTATO (
    ID SERIAL PRIMARY KEY NOT NULL,
    ATIVO BOOLEAN,
    CLIENTE INT,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    PESSOA VARCHAR(100),
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_CONTATO FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID),
    CONSTRAINT FK_CLIENTE_CONTATO FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID)
);

CREATE TABLE ANEXOS (
    ID SERIAL PRIMARY KEY NOT NULL,
    PROTOCOLO INT,
    DESCRICAO VARCHAR(100),
    ANEXO VARCHAR(100),--CAMINHO ONDE ESTARA O ARQUIVO
    DATAC TIMESTAMP,
    USERC INT,
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_ANEXOS FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID),
    CONSTRAINT FK_PROTOCOLO_ANEXOS FOREIGN KEY (PROTOCOLO) REFERENCES PROTOCOLO (ID)
);

CREATE TABLE OBSERVACAO (
    ID SERIAL PRIMARY KEY NOT NULL,
    PROTOCOLO INT,
    ATENDENTE INT,
    OBSERVACAO VARCHAR(8000),
    DATAC TIMESTAMP,
    USERC INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_OBS FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID),
    CONSTRAINT FK_PROTOCOLO_OBS FOREIGN KEY (PROTOCOLO) REFERENCES PROTOCOLO (ID),
    CONSTRAINT FK_ATENDENTE_OBS FOREIGN KEY (ATENDENTE) REFERENCES USUARIO (ID)
);

CREATE TABLE LOGS (
    ID SERIAL PRIMARY KEY NOT NULL,
    OPERACAO VARCHAR(100),
    TABELA VARCHAR(100),
    COLUNA VARCHAR(100),
    VALORANTIGO VARCHAR(500),
    VALORNOVO VARCHAR(500),
    DATAM TIMESTAMP,
    USERM INT,
    EMPRESA INT,
    CONSTRAINT FK_EMPRESA_LOGS FOREIGN KEY (EMPRESA) REFERENCES EMPRESA (ID)
);