version: '3'
services:
  adonis_app:
    build:
      context: .
      dockerfile: adonis/Dockerfile
    volumes:
    - ../back:/home/node/app
    - ../back:/home/node/app/node_modules
    ports:
    - 3333:3333
    depends_on:
      - pg
  
#    env_file:
#      - ../back/.env
#    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

#  node-server:
#    container_name: node-server
#    image: "node:16"
#    user: "node"
#    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=production
#    volumes:
#      - ../back:/home/node/app
#    ports:
#      - 3333:3333
#    command: "npm start"
  node-client:
    container_name: node-client
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../front:/home/node/app
    ports:
      - 3000:3000
    command: "npm start"
    links:
      - adonis_app
  pg:
    build: ./postgreSQL
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: oficina
      POSTGRES_PASSWORD: oficina
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgreSQL/data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'