const PREFIX = '@PROTOCOL/';

export const SET_PROTOCOL = `${PREFIX}SET_PROTOCOL`;
export const SET_SELECTED_PROTOCOL = `${PREFIX}SET_SELECTED_PROTOCOL`;
export const SET_LOADING = `${PREFIX}SET_LOADING`;
export const SET_SAVING = `${PREFIX}SET_SAVING`;
// export const DELETE = `${PREFIX}DELETE`;
